Fixed remaining linker issues and successfully built cesm for Ubuntu20.04LTS
* gptl: Added compile def -DFORTRANUNDERSCORE to fix linker failures due to unresolved gptl functions (e.g. "undefined reference to `gptlstart_")
* mct: Specified expected output static libraries
* csm_share: Added missing source file shr_reprosumx86.c. Arranged sources in alphabetical order for readability
* clm5: Added dependency to LAPACK. Used a more robust FindLAPACK.cmake module taken from https://github.com/scivision/lapack-cmake-meson/blob/02c08a55ed3a2e304923bb3f97d7114d50557a6d/cmake/Modules/FindLAPACK.cmake