Improve create_test output by dumping case errors directly to screen.
BEFORE:

Finished MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.melvin_gnu in 1.511061 seconds (FAIL). [COMPLETED 2 of 8] Case dir: /home/jgfouca/acme/scratch/TESTBUILDFAIL_P1.f19_g16_rx1.A.melvin_gnu.20170418_112029_6ygq0x

AFTER

Finished MODEL_BUILD for test TESTBUILDFAIL_P1.f19_g16_rx1.A.melvin_gnu in 1.511061 seconds (FAIL). [COMPLETED 2 of 8]
    Case dir: /home/jgfouca/acme/scratch/TESTBUILDFAIL_P1.f19_g16_rx1.A.melvin_gnu.20170418_112029_6ygq0x
    Errors were:
        Building test for TESTBUILDFAIL in directory /home/jgfouca/acme/scratch/TESTBUILDFAIL_P1.f19_g16_rx1.A.melvin_gnu.20170418_112029_6ygq0x
        Exception during build:
        ERROR: Intentional fail for testing infrastructure
        Traceback (most recent call last):
          File "/home/jgfouca/cime_yetanother/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 87, in build
            model_only=(phase_name==MODEL_BUILD_PHASE))
          File "/home/jgfouca/cime_yetanother/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 523, in build_phase
            expect(False, "Intentional fail for testing infrastructure")
          File "/home/jgfouca/cime_yetanother/scripts/Tools/../../scripts/lib/CIME/utils.py", line 29, in expect
            raise exc_type("%s %s"%(error_prefix,error_msg))
        SystemExit: ERROR: Intentional fail for testing infrastructure