Fix for testreporter.py script.  Was getting "ERROR: locked", and "AttributeError: 'NoneType' object has no attribute 'xml_element'", error messages.
testreporter.py is only used to populate the CESM testing database.

Test suite: scripts_regression_tests
Test baseline:
Test namelist changes:
Test status: bit for bit

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

Code review: